// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// AUTO-GENERATED by scripts/version_bump.py — do not edit by hand.
// Manual fields are version.txt (MAJOR.MINOR) and build_number.txt.
#ifndef BOSEFIX32_VERSION_H
#define BOSEFIX32_VERSION_H

#define FW_NAME           "SixBack"
#define FW_VERSION_MAJOR  0
#define FW_VERSION_MINOR  8
#define FW_VERSION_BUILD  1895

#define FW_VERSION_STRING "0.8.38"
#define FW_BUILD_DATE     "2026-07-30 21:49:15"

#endif // BOSEFIX32_VERSION_H
