// SPDX-License-Identifier: GPL-3.0-or-later
// AUTO-GENERATED by scripts/version_bump.py — do not edit by hand.
// Manual fields are version.txt (MAJOR.MINOR) and build_number.txt.
#ifndef BOSEFIX32_VERSION_H
#define BOSEFIX32_VERSION_H

#define FW_NAME           "BoseFix32"
#define FW_VERSION_MAJOR  0
#define FW_VERSION_MINOR  5
#define FW_VERSION_BUILD  372

#define FW_VERSION_STRING "0.5.372"
#define FW_BUILD_DATE     "2026-05-19 18:01:35"

#endif // BOSEFIX32_VERSION_H
